---

definitions:
  stringOrList:
    oneOf:
      - type: string
      - type: array
        items:
          type: string
  options:
    type: object
    properties:
      force-sequential:
        type: string
    additionalProperties: false
  global-request:
    type: object
    properties:
      base-url:
        type: string
      auth:
        $ref: '#/definitions/auth'
      headers:
        $ref: '#/definitions/headers'
    additionalProperties: false
  scenario:
    type: object
    properties:
      name:
        type: string
      dependencies:
        $ref: '#/definitions/stringOrList'
      tests:
        type: array
        items:
          $ref: '#/definitions/test'
    additionalProperties: false
    required:
      - name
      - tests
  test:
    type: object
    properties:
      name:
        type: string
      request:
        $ref: '#/definitions/request'
      response:
        $ref: '#/definitions/response'
    additionalProperties: false
    required:
      - request
  request:
    type: object
    properties:
      uri:
        type: string
      method:
        type: string
        enum:
          - get
          - post
          - put
          - patch
          - delete
          - options
      headers:
        $ref: '#/definitions/headers'
      auth:
        $ref: '#/definitions/auth'
      body:
        type: string
      json-body: {}
    additionalProperties: false
    required:
      - uri
  response:
    type: object
    properties:
      status:
        anyOf:
          - type: string
          - type: number
      headers:
        $ref: '#/definitions/headers'
      body:
        type: string
      extract:
        type: string
    additionalProperties: false
  headers:
    type: object
    additionalProperties:
      $ref: '#/definitions/stringOrList'
  auth:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
    additionalProperties: false
    required:
      - username
      - password

type: object
properties:
  options:
    $ref: '#/definitions/options'
  global-request:
    $ref: '#/definitions/global-request'
  scenarios:
    type: array
    items:
      $ref: '#/definitions/scenario'
  include:
    $ref: '#/definitions/stringOrList'
additionalProperties: false
