---

definitions:
  stringOrList:
    oneOf:
      - type: string
      - type: array
        items:
          type: string
  options:
    type: object
    properties:
      force-sequential:
        type: boolean
      max-parallelism:
        type: integer
    additionalProperties: false
  global-request:
    type: object
    properties:
      base-url:
        type: string
      auth:
        $ref: '#/definitions/auth'
      headers:
        $ref: '#/definitions/headers'
    additionalProperties: false
  headers:
    type: object
    additionalProperties:
      $ref: '#/definitions/stringOrList'
  auth:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
    additionalProperties: false
    required:
      - username
      - password

type: object
properties:
  options:
    $ref: '#/definitions/options'
  global-request:
    $ref: '#/definitions/global-request'
  scenarios:
    type: array
  include:
    $ref: '#/definitions/stringOrList'
additionalProperties: false
